### ISSUE TITLE
Lost dependency

### ISSUE THREAD

**Issue by FedericoPecora** [FedericoPecora/coordination_oru#5]
I sometimes get the following error, but I have thus far failed to find a way to replicate it:
``java.lang.Error: FIXME! Lost dependency and order cannot be restored! Key value not found
	at se.oru.coordination.coordination_oru.TrajectoryEnvelopeCoordinator.localCheckAndRevise(TrajectoryEnvelopeCoordinator.java:812)
	at se.oru.coordination.coordination_oru.TrajectoryEnvelopeCoordinator.updateDependencies(TrajectoryEnvelopeCoordinator.java:575)
	at se.oru.coordination.coordination_oru.TrajectoryEnvelopeCoordinator.replacePath(TrajectoryEnvelopeCoordinator.java:1251)
	at se.oru.coordination.coordination_oru.TrajectoryEnvelopeCoordinator.rePlanPath(TrajectoryEnvelopeCoordinator.java:1053)
	at se.oru.coordination.coordination_oru.TrajectoryEnvelopeCoordinator$1.run(TrajectoryEnvelopeCoordinator.java:993)``

**Comment by annamannucci** [comment]
I added more prints to debug this case. Please, send me a screenshot if it will happen again.

**Comment by annamannucci** [comment]
I probably solved just one of the two issues, that is, preserving correctly the last communicated critical point before re-planning. However, the replacePath is missing some cases in which the previous order should be restored (not all the overlaps are considered). I just add a reminder for tomorrow.

**Comment by annamannucci** [comment]
The bug is clear (all the "non-reversible" critical sections in allCriticalSections should be always associated to a dependency in CSToDepsOrder, but sometimes this dep is missed), but it is still not clear its origin. 

Anyway, **the last commit is able to safely solve the problem for the localCheckAndRevise in most of the cases** (I tested more than 130 re-plan and it seems to be fine). 

**I should still understand/fix the main cause in and propagate this recovery strategy to the globalCheckAndRevise**, **but the localCheckAndRevise should be fine now.** Let me know in case of issues.

Best.

**Comment by annamannucci** [comment]
The solution seems to be quite stable, so I'm closing this issue. Let me know in case of any problems.
